import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NBA Conference Finals East - Boston vs Miami',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        {/* <h1>Isto deve aparecer em todas as páginas</h1> */}
        {children}
        </body>
    </html>
  )
}
